package trilogiz;

import java.awt.Color;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.Properties;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ryzen
 */
public class Server_Setting extends javax.swing.JFrame {

    /**
     * Creates new form Server_Setting
     */
    public Server_Setting() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LoginText = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        LabelServerDB = new javax.swing.JLabel();
        LabelServerDB_in = new javax.swing.JTextField();
        LabelUsernameDB_in = new javax.swing.JTextField();
        LabelUsernameDB = new javax.swing.JLabel();
        LabePasswordDB_in = new javax.swing.JTextField();
        LabePasswordDB = new javax.swing.JLabel();
        LabelDatabaseDB = new javax.swing.JLabel();
        LabelDatabaseDB_in = new javax.swing.JTextField();
        LabelSaveDB = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(102, 102, 102));

        LoginText.setBackground(new java.awt.Color(255, 255, 255));
        LoginText.setFont(new java.awt.Font("Bebas Neue", 0, 36)); // NOI18N
        LoginText.setForeground(new java.awt.Color(51, 51, 51));
        LoginText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LoginText.setText("server setting");

        LabelServerDB.setFont(new java.awt.Font("NewsGoth BT", 0, 14)); // NOI18N
        LabelServerDB.setForeground(new java.awt.Color(102, 102, 102));
        LabelServerDB.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LabelServerDB.setText("SERVER :");

        LabelServerDB_in.setBackground(new java.awt.Color(255, 255, 255));
        LabelServerDB_in.setForeground(new java.awt.Color(0, 0, 0));
        LabelServerDB_in.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        LabelServerDB_in.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LabelServerDB_inActionPerformed(evt);
            }
        });

        LabelUsernameDB_in.setBackground(new java.awt.Color(255, 255, 255));
        LabelUsernameDB_in.setForeground(new java.awt.Color(0, 0, 0));
        LabelUsernameDB_in.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        LabelUsernameDB_in.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LabelUsernameDB_inActionPerformed(evt);
            }
        });
        LabelUsernameDB_in.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                LabelUsernameDB_inKeyPressed(evt);
            }
        });

        LabelUsernameDB.setFont(new java.awt.Font("NewsGoth BT", 0, 14)); // NOI18N
        LabelUsernameDB.setForeground(new java.awt.Color(102, 102, 102));
        LabelUsernameDB.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LabelUsernameDB.setText("USERNAME :");

        LabePasswordDB_in.setBackground(new java.awt.Color(255, 255, 255));
        LabePasswordDB_in.setForeground(new java.awt.Color(0, 0, 0));
        LabePasswordDB_in.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        LabePasswordDB_in.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LabePasswordDB_inActionPerformed(evt);
            }
        });
        LabePasswordDB_in.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                LabePasswordDB_inKeyPressed(evt);
            }
        });

        LabePasswordDB.setFont(new java.awt.Font("NewsGoth BT", 0, 14)); // NOI18N
        LabePasswordDB.setForeground(new java.awt.Color(102, 102, 102));
        LabePasswordDB.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LabePasswordDB.setText("PASSWORD :");

        LabelDatabaseDB.setFont(new java.awt.Font("NewsGoth BT", 0, 14)); // NOI18N
        LabelDatabaseDB.setForeground(new java.awt.Color(102, 102, 102));
        LabelDatabaseDB.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LabelDatabaseDB.setText("DATABASE :");

        LabelDatabaseDB_in.setBackground(new java.awt.Color(255, 255, 255));
        LabelDatabaseDB_in.setForeground(new java.awt.Color(0, 0, 0));
        LabelDatabaseDB_in.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        LabelDatabaseDB_in.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LabelDatabaseDB_inActionPerformed(evt);
            }
        });
        LabelDatabaseDB_in.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                LabelDatabaseDB_inKeyPressed(evt);
            }
        });

        LabelSaveDB.setBackground(new java.awt.Color(102, 102, 102));
        LabelSaveDB.setFont(new java.awt.Font("Bebas Neue", 0, 24)); // NOI18N
        LabelSaveDB.setForeground(new java.awt.Color(255, 255, 255));
        LabelSaveDB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelSaveDB.setText("Save");
        LabelSaveDB.setOpaque(true);
        LabelSaveDB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelSaveDBMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LabelSaveDBMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LabelSaveDBMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(276, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LoginText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1)
                    .addComponent(LabelServerDB)
                    .addComponent(LabelServerDB_in)
                    .addComponent(LabelUsernameDB_in)
                    .addComponent(LabelUsernameDB)
                    .addComponent(LabePasswordDB_in)
                    .addComponent(LabePasswordDB)
                    .addComponent(LabelDatabaseDB)
                    .addComponent(LabelDatabaseDB_in)
                    .addComponent(LabelSaveDB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(252, 252, 252))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LoginText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LabelServerDB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelServerDB_in, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LabelUsernameDB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelUsernameDB_in, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LabePasswordDB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabePasswordDB_in, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LabelDatabaseDB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelDatabaseDB_in, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(LabelSaveDB, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void LabelServerDB_inActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LabelServerDB_inActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LabelServerDB_inActionPerformed

    private void LabelUsernameDB_inActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LabelUsernameDB_inActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LabelUsernameDB_inActionPerformed

    private void LabelUsernameDB_inKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LabelUsernameDB_inKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_LabelUsernameDB_inKeyPressed

    private void LabePasswordDB_inActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LabePasswordDB_inActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LabePasswordDB_inActionPerformed

    private void LabePasswordDB_inKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LabePasswordDB_inKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_LabePasswordDB_inKeyPressed

    private void LabelDatabaseDB_inActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LabelDatabaseDB_inActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LabelDatabaseDB_inActionPerformed

    private void LabelDatabaseDB_inKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LabelDatabaseDB_inKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_LabelDatabaseDB_inKeyPressed

    private void LabelSaveDBMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelSaveDBMouseEntered
        // TODO add your handling code here:
        LabelSaveDB.setBackground(new Color(153,153,153));
    }//GEN-LAST:event_LabelSaveDBMouseEntered

    private void LabelSaveDBMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelSaveDBMouseExited
        // TODO add your handling code here:
        LabelSaveDB.setBackground(new Color(102,102,102));
    }//GEN-LAST:event_LabelSaveDBMouseExited

    private void LabelSaveDBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelSaveDBMouseClicked
        // TODO add your handling code here:
        try (FileOutputStream outputfile = new FileOutputStream("config.properties")) {

            Properties prop = new Properties();
            prop.setProperty("server", LabelServerDB_in.getText());
            prop.setProperty("username", LabelUsernameDB_in.getText());
            prop.setProperty("password", LabePasswordDB_in.getText());
            prop.setProperty("db", LabelDatabaseDB_in.getText());
            // save properties to project root folder
            prop.store(outputfile, "#Config Server");
            System.out.println("Writing" + prop);

        } catch (IOException io) {
            io.printStackTrace();
            System.out.println("File Not Found or Empty or Wrong");
        }
        System.exit(0);
    }//GEN-LAST:event_LabelSaveDBMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        if(Trilogiz.lgf.isVisible()){
        Trilogiz.lgf.setEnabled(true);
        }else{
        Trilogiz.lgf.setVisible(true);
        }
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Server_Setting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Server_Setting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Server_Setting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Server_Setting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Server_Setting().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabePasswordDB;
    javax.swing.JTextField LabePasswordDB_in;
    private javax.swing.JLabel LabelDatabaseDB;
    javax.swing.JTextField LabelDatabaseDB_in;
    private javax.swing.JLabel LabelSaveDB;
    private javax.swing.JLabel LabelServerDB;
    javax.swing.JTextField LabelServerDB_in;
    private javax.swing.JLabel LabelUsernameDB;
    javax.swing.JTextField LabelUsernameDB_in;
    private javax.swing.JLabel LoginText;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
