/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trilogiz;

import java.awt.Color;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Arrays;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;

import javax.swing.table.DefaultTableModel;
import org.freixas.jcalendar.DateEvent;

/**
 *
 * @author ryzen
 */
public class Setter extends javax.swing.JFrame {
public static int idnow;
public static java.util.Date tanggalsekarangDate = new GregorianCalendar(Integer.parseInt(Trilogiz.tanggalsekarang.substring(0,4)), Integer.parseInt(Trilogiz.tanggalsekarang.substring(4,6))-1, Integer.parseInt(Trilogiz.tanggalsekarang.substring(6,8))).getTime();;
    /**
     * Creates new form Setter
     */
    public String statusjob(){
        String status;
        if(Trilogiz.job == 1){
            status = "Setter";
        }else if(Trilogiz.job == 2){
            status = "Operator";
        }
        else{
            status = null;
        }
        return status;
    }
    public Setter() {
        initComponents();
        read_data.getlastid("barang"+Trilogiz.tanggalsekarang, LabelID_status);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userpanel = new javax.swing.JPanel();
        LabelUsername = new javax.swing.JLabel();
        LabelNama = new javax.swing.JLabel();
        LabelJob = new javax.swing.JLabel();
        LabelNama_status = new javax.swing.JLabel();
        LabelJob_status = new javax.swing.JLabel();
        LabelUsername_status = new javax.swing.JLabel();
        LabelTanggal = new javax.swing.JLabel();
        LabelID_status = new javax.swing.JLabel();
        LabelID = new javax.swing.JLabel();
        LabelCekinputdata = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        LabelCekdataorder = new javax.swing.JLabel();
        LabelTanggal_status = new org.freixas.jcalendar.JCalendarCombo();
        jPanel1 = new javax.swing.JPanel();
        LabelJenisBahan = new javax.swing.JLabel();
        LabelUkuran = new javax.swing.JLabel();
        LabelNamaSetter = new javax.swing.JLabel();
        LabelNamaCustomer = new javax.swing.JLabel();
        LabelSubmit = new javax.swing.JLabel();
        LabelKeterangan1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        LabelKeterangan_input = new javax.swing.JTextArea();
        LabelNamaCustomer_input = new javax.swing.JTextField();
        LabelJenisBahan_input = new javax.swing.JTextField();
        LabelUkuran_input = new javax.swing.JTextField();
        LabelNamaSetter_input = new javax.swing.JTextField();
        LabelHarga_input = new javax.swing.JTextField();
        LabelHarga = new javax.swing.JLabel();
        LabelPootnganHarga = new javax.swing.JLabel();
        LabelQty = new javax.swing.JLabel();
        LabelPootnganHarga_input = new javax.swing.JTextField();
        LabelQty_input = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        NamaCustEdit = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        LabelStatusEdit = new javax.swing.JLabel();
        LabelJenisBahanEdit = new javax.swing.JLabel();
        LabelSetterEdit = new javax.swing.JLabel();
        LabelIDEdit = new javax.swing.JLabel();
        LabelUkuranEdit = new javax.swing.JLabel();
        EditNamaCustomer_input = new javax.swing.JTextField();
        EditJenisBahan_input = new javax.swing.JTextField();
        EditSetter_input = new javax.swing.JTextField();
        EditID_input = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        EditUkuran_input = new javax.swing.JTextField();
        LabelQtyEdit1 = new javax.swing.JLabel();
        EditQty_input = new javax.swing.JTextField();
        Editharga_input = new javax.swing.JTextField();
        LabelHargaEdit = new javax.swing.JLabel();
        LabelpotHargaEdit = new javax.swing.JLabel();
        EditpotHarga_input = new javax.swing.JTextField();
        LabelKetEdit = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        EditKeterangan_input = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();
        EditStatus_input = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Setter Tab");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        userpanel.setBackground(new java.awt.Color(44, 62, 80));
        userpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabelUsername.setBackground(new java.awt.Color(211, 84, 0));
        LabelUsername.setFont(new java.awt.Font("Geometr706 BlkCn BT", 0, 14)); // NOI18N
        LabelUsername.setForeground(new java.awt.Color(255, 255, 255));
        LabelUsername.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelUsername.setText("USERNAME");
        LabelUsername.setOpaque(true);
        userpanel.add(LabelUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 101, 27));

        LabelNama.setBackground(new java.awt.Color(211, 84, 0));
        LabelNama.setFont(new java.awt.Font("Geometr706 BlkCn BT", 0, 14)); // NOI18N
        LabelNama.setForeground(new java.awt.Color(255, 255, 255));
        LabelNama.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelNama.setText("NAMA");
        LabelNama.setOpaque(true);
        userpanel.add(LabelNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 101, 27));

        LabelJob.setBackground(new java.awt.Color(211, 84, 0));
        LabelJob.setFont(new java.awt.Font("Geometr706 BlkCn BT", 0, 14)); // NOI18N
        LabelJob.setForeground(new java.awt.Color(255, 255, 255));
        LabelJob.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelJob.setText("JOB");
        LabelJob.setOpaque(true);
        userpanel.add(LabelJob, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 101, 27));

        LabelNama_status.setBackground(new java.awt.Color(230, 126, 34));
        LabelNama_status.setFont(new java.awt.Font("Geometr706 BlkCn BT", 0, 14)); // NOI18N
        LabelNama_status.setForeground(new java.awt.Color(255, 255, 255));
        LabelNama_status.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelNama_status.setOpaque(true);
        userpanel.add(LabelNama_status, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 240, 27));
        LabelNama_status.setText(Trilogiz.namauser);

        LabelJob_status.setBackground(new java.awt.Color(230, 126, 34));
        LabelJob_status.setFont(new java.awt.Font("Geometr706 BlkCn BT", 0, 14)); // NOI18N
        LabelJob_status.setForeground(new java.awt.Color(255, 255, 255));
        LabelJob_status.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelJob_status.setOpaque(true);
        userpanel.add(LabelJob_status, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 240, 27));
        LabelJob_status.setText(statusjob());

        LabelUsername_status.setBackground(new java.awt.Color(230, 126, 34));
        LabelUsername_status.setFont(new java.awt.Font("Geometr706 BlkCn BT", 0, 14)); // NOI18N
        LabelUsername_status.setForeground(new java.awt.Color(255, 255, 255));
        LabelUsername_status.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelUsername_status.setOpaque(true);
        userpanel.add(LabelUsername_status, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 240, 27));
        LabelUsername_status.setText(Trilogiz.username);

        LabelTanggal.setBackground(new java.awt.Color(211, 84, 0));
        LabelTanggal.setFont(new java.awt.Font("Geometr706 BlkCn BT", 0, 14)); // NOI18N
        LabelTanggal.setForeground(new java.awt.Color(255, 255, 255));
        LabelTanggal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelTanggal.setText("TANGGGAL");
        LabelTanggal.setOpaque(true);
        userpanel.add(LabelTanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 101, 27));

        LabelID_status.setBackground(new java.awt.Color(230, 126, 34));
        LabelID_status.setFont(new java.awt.Font("Geometr706 BlkCn BT", 0, 14)); // NOI18N
        LabelID_status.setForeground(new java.awt.Color(255, 255, 255));
        LabelID_status.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelID_status.setOpaque(true);
        userpanel.add(LabelID_status, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 40, 240, 27));

        LabelID.setBackground(new java.awt.Color(211, 84, 0));
        LabelID.setFont(new java.awt.Font("Geometr706 BlkCn BT", 0, 14)); // NOI18N
        LabelID.setForeground(new java.awt.Color(255, 255, 255));
        LabelID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelID.setText("ID SELANJUTNYA");
        LabelID.setOpaque(true);
        userpanel.add(LabelID, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 40, 101, 27));

        LabelCekinputdata.setBackground(new java.awt.Color(41, 128, 185));
        LabelCekinputdata.setFont(new java.awt.Font("Geometr706 BlkCn BT", 0, 14)); // NOI18N
        LabelCekinputdata.setForeground(new java.awt.Color(255, 255, 255));
        LabelCekinputdata.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelCekinputdata.setText("Input Data");
        LabelCekinputdata.setOpaque(true);
        LabelCekinputdata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelCekinputdataMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LabelCekinputdataMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LabelCekinputdataMouseExited(evt);
            }
        });
        userpanel.add(LabelCekinputdata, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 70, 150, 30));

        jButton1.setText("Refresh");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        userpanel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 30, -1, -1));

        LabelCekdataorder.setBackground(new java.awt.Color(41, 128, 185));
        LabelCekdataorder.setFont(new java.awt.Font("Geometr706 BlkCn BT", 0, 14)); // NOI18N
        LabelCekdataorder.setForeground(new java.awt.Color(255, 255, 255));
        LabelCekdataorder.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelCekdataorder.setText("Cek Data order");
        LabelCekdataorder.setOpaque(true);
        LabelCekdataorder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelCekdataorderMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LabelCekdataorderMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LabelCekdataorderMouseExited(evt);
            }
        });
        userpanel.add(LabelCekdataorder, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, 340, 30));

        LabelTanggal_status.setBorder(null);
        LabelTanggal_status.setOpaque(false);
        LabelTanggal_status.addDateListener(new org.freixas.jcalendar.DateListener() {
            public void dateChanged(org.freixas.jcalendar.DateEvent evt) {
                LabelTanggal_statusDateChanged(evt);
            }
        });
        userpanel.add(LabelTanggal_status, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, 240, 27));
        LabelTanggal_status.setDate(tanggalsekarangDate);

        getContentPane().add(userpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 110));

        jPanel1.setBackground(new java.awt.Color(52, 73, 94));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabelJenisBahan.setBackground(new java.awt.Color(211, 84, 0));
        LabelJenisBahan.setFont(new java.awt.Font("Geometr706 BlkCn BT", 0, 14)); // NOI18N
        LabelJenisBahan.setForeground(new java.awt.Color(255, 255, 255));
        LabelJenisBahan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelJenisBahan.setText("Jenis Bahan");
        LabelJenisBahan.setOpaque(true);
        jPanel1.add(LabelJenisBahan, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, 101, 27));

        LabelUkuran.setBackground(new java.awt.Color(211, 84, 0));
        LabelUkuran.setFont(new java.awt.Font("Geometr706 BlkCn BT", 0, 14)); // NOI18N
        LabelUkuran.setForeground(new java.awt.Color(255, 255, 255));
        LabelUkuran.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelUkuran.setText("Ukuran");
        LabelUkuran.setOpaque(true);
        jPanel1.add(LabelUkuran, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, 101, 27));

        LabelNamaSetter.setBackground(new java.awt.Color(211, 84, 0));
        LabelNamaSetter.setFont(new java.awt.Font("Geometr706 BlkCn BT", 0, 14)); // NOI18N
        LabelNamaSetter.setForeground(new java.awt.Color(255, 255, 255));
        LabelNamaSetter.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelNamaSetter.setText("Nama Setter");
        LabelNamaSetter.setOpaque(true);
        jPanel1.add(LabelNamaSetter, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, 101, 27));

        LabelNamaCustomer.setBackground(new java.awt.Color(211, 84, 0));
        LabelNamaCustomer.setFont(new java.awt.Font("Geometr706 BlkCn BT", 0, 14)); // NOI18N
        LabelNamaCustomer.setForeground(new java.awt.Color(255, 255, 255));
        LabelNamaCustomer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelNamaCustomer.setText("Nama Customer");
        LabelNamaCustomer.setOpaque(true);
        jPanel1.add(LabelNamaCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, 101, 27));

        LabelSubmit.setBackground(new java.awt.Color(41, 128, 185));
        LabelSubmit.setFont(new java.awt.Font("Geometr706 BlkCn BT", 0, 14)); // NOI18N
        LabelSubmit.setForeground(new java.awt.Color(255, 255, 255));
        LabelSubmit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelSubmit.setText("DAFTARKAN PESANAN");
        LabelSubmit.setOpaque(true);
        LabelSubmit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelSubmitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LabelSubmitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LabelSubmitMouseExited(evt);
            }
        });
        jPanel1.add(LabelSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 480, 340, 30));

        LabelKeterangan1.setBackground(new java.awt.Color(211, 84, 0));
        LabelKeterangan1.setFont(new java.awt.Font("Geometr706 BlkCn BT", 0, 14)); // NOI18N
        LabelKeterangan1.setForeground(new java.awt.Color(255, 255, 255));
        LabelKeterangan1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelKeterangan1.setText("Keterangan");
        LabelKeterangan1.setOpaque(true);
        jPanel1.add(LabelKeterangan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, 340, 30));

        LabelKeterangan_input.setBackground(new java.awt.Color(255, 255, 255));
        LabelKeterangan_input.setColumns(20);
        LabelKeterangan_input.setFont(new java.awt.Font("Geometr706 BlkCn BT", 0, 14)); // NOI18N
        LabelKeterangan_input.setLineWrap(true);
        LabelKeterangan_input.setRows(5);
        LabelKeterangan_input.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 126, 34)));
        jScrollPane1.setViewportView(LabelKeterangan_input);
        LabelKeterangan_input.getAccessibleContext().setAccessibleName("");

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 370, 340, 100));

        LabelNamaCustomer_input.setBackground(new java.awt.Color(255, 255, 255));
        LabelNamaCustomer_input.setFont(new java.awt.Font("Geometr706 BlkCn BT", 0, 14)); // NOI18N
        LabelNamaCustomer_input.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 126, 34)));
        jPanel1.add(LabelNamaCustomer_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, 230, 27));

        LabelJenisBahan_input.setBackground(new java.awt.Color(255, 255, 255));
        LabelJenisBahan_input.setFont(new java.awt.Font("Geometr706 BlkCn BT", 0, 14)); // NOI18N
        LabelJenisBahan_input.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 126, 34)));
        jPanel1.add(LabelJenisBahan_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, 230, 27));

        LabelUkuran_input.setBackground(new java.awt.Color(255, 255, 255));
        LabelUkuran_input.setFont(new java.awt.Font("Geometr706 BlkCn BT", 0, 14)); // NOI18N
        LabelUkuran_input.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 126, 34)));
        jPanel1.add(LabelUkuran_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, 230, 27));

        LabelNamaSetter_input.setBackground(new java.awt.Color(255, 255, 255));
        LabelNamaSetter_input.setFont(new java.awt.Font("Geometr706 BlkCn BT", 0, 14)); // NOI18N
        LabelNamaSetter_input.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 126, 34)));
        jPanel1.add(LabelNamaSetter_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 220, 230, 27));
        LabelNamaSetter_input.setText(Trilogiz.namauser);

        LabelHarga_input.setBackground(new java.awt.Color(255, 255, 255));
        LabelHarga_input.setFont(new java.awt.Font("Geometr706 BlkCn BT", 0, 14)); // NOI18N
        LabelHarga_input.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 126, 34)));
        LabelHarga_input.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                LabelHarga_inputKeyTyped(evt);
            }
        });
        jPanel1.add(LabelHarga_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 310, 170, 27));
        LabelNamaSetter_input.setText(Trilogiz.namauser);

        LabelHarga.setBackground(new java.awt.Color(211, 84, 0));
        LabelHarga.setFont(new java.awt.Font("Geometr706 BlkCn BT", 0, 14)); // NOI18N
        LabelHarga.setForeground(new java.awt.Color(255, 255, 255));
        LabelHarga.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelHarga.setText("Harga");
        LabelHarga.setOpaque(true);
        jPanel1.add(LabelHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, 170, 27));

        LabelPootnganHarga.setBackground(new java.awt.Color(211, 84, 0));
        LabelPootnganHarga.setFont(new java.awt.Font("Geometr706 BlkCn BT", 0, 14)); // NOI18N
        LabelPootnganHarga.setForeground(new java.awt.Color(255, 255, 255));
        LabelPootnganHarga.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelPootnganHarga.setText("Potongan Harga");
        LabelPootnganHarga.setOpaque(true);
        jPanel1.add(LabelPootnganHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 280, 170, 27));

        LabelQty.setBackground(new java.awt.Color(211, 84, 0));
        LabelQty.setFont(new java.awt.Font("Geometr706 BlkCn BT", 0, 14)); // NOI18N
        LabelQty.setForeground(new java.awt.Color(255, 255, 255));
        LabelQty.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelQty.setText("Qty(meter)");
        LabelQty.setOpaque(true);
        jPanel1.add(LabelQty, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, 101, 27));

        LabelPootnganHarga_input.setBackground(new java.awt.Color(255, 255, 255));
        LabelPootnganHarga_input.setFont(new java.awt.Font("Geometr706 BlkCn BT", 0, 14)); // NOI18N
        LabelPootnganHarga_input.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 126, 34)));
        LabelPootnganHarga_input.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                LabelPootnganHarga_inputKeyTyped(evt);
            }
        });
        jPanel1.add(LabelPootnganHarga_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 310, 170, 27));
        LabelNamaSetter_input.setText(Trilogiz.namauser);

        LabelQty_input.setBackground(new java.awt.Color(255, 255, 255));
        LabelQty_input.setFont(new java.awt.Font("Geometr706 BlkCn BT", 0, 14)); // NOI18N
        LabelQty_input.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 126, 34)));
        LabelQty_input.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                LabelQty_inputKeyTyped(evt);
            }
        });
        jPanel1.add(LabelQty_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 250, 230, 27));
        LabelNamaSetter_input.setText(Trilogiz.namauser);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 520));

        jPanel2.setBackground(new java.awt.Color(52, 73, 94));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NamaCustEdit.setBackground(new java.awt.Color(211, 84, 0));
        NamaCustEdit.setFont(new java.awt.Font("Geometr706 BlkCn BT", 0, 14)); // NOI18N
        NamaCustEdit.setForeground(new java.awt.Color(255, 255, 255));
        NamaCustEdit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NamaCustEdit.setText("Nama Customer");
        NamaCustEdit.setOpaque(true);
        jPanel2.add(NamaCustEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 101, 27));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nama", "Jenis Bahan", "Status"
            }
        ));
        jScrollPane3.setViewportView(jTable1);
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        jScrollPane3.getViewport().setBackground(new Color(52,73,94));
        String[][] databarang = new read_data(new String[]{"id","jenis_bahan","ukuran","keterangan","nama_customer","nama_setter","qty"},new String[]{"int","string","string","string","string","string","int"},"barang"+Trilogiz.tanggalsekarang).read_data();
        String[][] datastatus = new read_data(new String[]{"id","pengerjaan","harga","potongan_harga"},new String[]{"int","string","int","int"},"status"+Trilogiz.tanggalsekarang).read_data();
        if(databarang == null){}else{
            for(int i=0;i<databarang.length;i++){
                model.addRow(new Object[]{databarang[i][0],databarang[i][4],databarang[i][1],datastatus[i][1]});
            }
        }

        jPanel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 110, -1, 410));

        LabelStatusEdit.setBackground(new java.awt.Color(211, 84, 0));
        LabelStatusEdit.setFont(new java.awt.Font("Geometr706 BlkCn BT", 0, 14)); // NOI18N
        LabelStatusEdit.setForeground(new java.awt.Color(255, 255, 255));
        LabelStatusEdit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelStatusEdit.setText("Status");
        LabelStatusEdit.setOpaque(true);
        jPanel2.add(LabelStatusEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 101, 27));

        LabelJenisBahanEdit.setBackground(new java.awt.Color(211, 84, 0));
        LabelJenisBahanEdit.setFont(new java.awt.Font("Geometr706 BlkCn BT", 0, 14)); // NOI18N
        LabelJenisBahanEdit.setForeground(new java.awt.Color(255, 255, 255));
        LabelJenisBahanEdit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelJenisBahanEdit.setText("Jenis Bahan");
        LabelJenisBahanEdit.setOpaque(true);
        jPanel2.add(LabelJenisBahanEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 101, 27));

        LabelSetterEdit.setBackground(new java.awt.Color(211, 84, 0));
        LabelSetterEdit.setFont(new java.awt.Font("Geometr706 BlkCn BT", 0, 14)); // NOI18N
        LabelSetterEdit.setForeground(new java.awt.Color(255, 255, 255));
        LabelSetterEdit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelSetterEdit.setText("Setter");
        LabelSetterEdit.setOpaque(true);
        jPanel2.add(LabelSetterEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 101, 27));

        LabelIDEdit.setBackground(new java.awt.Color(211, 84, 0));
        LabelIDEdit.setFont(new java.awt.Font("Geometr706 BlkCn BT", 0, 14)); // NOI18N
        LabelIDEdit.setForeground(new java.awt.Color(255, 255, 255));
        LabelIDEdit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelIDEdit.setText("ID");
        LabelIDEdit.setOpaque(true);
        jPanel2.add(LabelIDEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 101, 27));

        LabelUkuranEdit.setBackground(new java.awt.Color(211, 84, 0));
        LabelUkuranEdit.setFont(new java.awt.Font("Geometr706 BlkCn BT", 0, 14)); // NOI18N
        LabelUkuranEdit.setForeground(new java.awt.Color(255, 255, 255));
        LabelUkuranEdit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelUkuranEdit.setText("Ukuran");
        LabelUkuranEdit.setOpaque(true);
        jPanel2.add(LabelUkuranEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 101, 27));

        EditNamaCustomer_input.setBackground(new java.awt.Color(255, 255, 255));
        EditNamaCustomer_input.setFont(new java.awt.Font("Geometr706 BlkCn BT", 0, 14)); // NOI18N
        EditNamaCustomer_input.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(EditNamaCustomer_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 220, 27));

        EditJenisBahan_input.setBackground(new java.awt.Color(255, 255, 255));
        EditJenisBahan_input.setFont(new java.awt.Font("Geometr706 BlkCn BT", 0, 14)); // NOI18N
        EditJenisBahan_input.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(EditJenisBahan_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 220, 27));

        EditSetter_input.setBackground(new java.awt.Color(255, 255, 255));
        EditSetter_input.setFont(new java.awt.Font("Geometr706 BlkCn BT", 0, 14)); // NOI18N
        EditSetter_input.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(EditSetter_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 220, 27));

        EditID_input.setBackground(new java.awt.Color(255, 255, 255));
        EditID_input.setFont(new java.awt.Font("Geometr706 BlkCn BT", 0, 14)); // NOI18N
        EditID_input.setForeground(new java.awt.Color(0, 0, 0));
        EditID_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditID_inputActionPerformed(evt);
            }
        });
        EditID_input.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                EditID_inputKeyTyped(evt);
            }
        });
        jPanel2.add(EditID_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 170, 27));

        jButton2.setText("Edit");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, -1, -1));

        EditUkuran_input.setBackground(new java.awt.Color(255, 255, 255));
        EditUkuran_input.setFont(new java.awt.Font("Geometr706 BlkCn BT", 0, 14)); // NOI18N
        EditUkuran_input.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(EditUkuran_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 220, 27));

        LabelQtyEdit1.setBackground(new java.awt.Color(211, 84, 0));
        LabelQtyEdit1.setFont(new java.awt.Font("Geometr706 BlkCn BT", 0, 14)); // NOI18N
        LabelQtyEdit1.setForeground(new java.awt.Color(255, 255, 255));
        LabelQtyEdit1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelQtyEdit1.setText("Qty");
        LabelQtyEdit1.setOpaque(true);
        jPanel2.add(LabelQtyEdit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 101, 27));

        EditQty_input.setBackground(new java.awt.Color(255, 255, 255));
        EditQty_input.setFont(new java.awt.Font("Geometr706 BlkCn BT", 0, 14)); // NOI18N
        EditQty_input.setForeground(new java.awt.Color(0, 0, 0));
        EditQty_input.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                EditQty_inputKeyTyped(evt);
            }
        });
        jPanel2.add(EditQty_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 220, 27));

        Editharga_input.setBackground(new java.awt.Color(255, 255, 255));
        Editharga_input.setFont(new java.awt.Font("Geometr706 BlkCn BT", 0, 14)); // NOI18N
        Editharga_input.setForeground(new java.awt.Color(0, 0, 0));
        Editharga_input.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Editharga_inputKeyTyped(evt);
            }
        });
        jPanel2.add(Editharga_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, 220, 27));

        LabelHargaEdit.setBackground(new java.awt.Color(211, 84, 0));
        LabelHargaEdit.setFont(new java.awt.Font("Geometr706 BlkCn BT", 0, 14)); // NOI18N
        LabelHargaEdit.setForeground(new java.awt.Color(255, 255, 255));
        LabelHargaEdit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelHargaEdit.setText("Harga");
        LabelHargaEdit.setOpaque(true);
        jPanel2.add(LabelHargaEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 101, 27));

        LabelpotHargaEdit.setBackground(new java.awt.Color(211, 84, 0));
        LabelpotHargaEdit.setFont(new java.awt.Font("Geometr706 BlkCn BT", 0, 14)); // NOI18N
        LabelpotHargaEdit.setForeground(new java.awt.Color(255, 255, 255));
        LabelpotHargaEdit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelpotHargaEdit.setText("Pot.Harga");
        LabelpotHargaEdit.setOpaque(true);
        jPanel2.add(LabelpotHargaEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 101, 27));

        EditpotHarga_input.setBackground(new java.awt.Color(255, 255, 255));
        EditpotHarga_input.setFont(new java.awt.Font("Geometr706 BlkCn BT", 0, 14)); // NOI18N
        EditpotHarga_input.setForeground(new java.awt.Color(0, 0, 0));
        EditpotHarga_input.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                EditpotHarga_inputKeyTyped(evt);
            }
        });
        jPanel2.add(EditpotHarga_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, 220, 27));

        LabelKetEdit.setBackground(new java.awt.Color(211, 84, 0));
        LabelKetEdit.setFont(new java.awt.Font("Geometr706 BlkCn BT", 0, 14)); // NOI18N
        LabelKetEdit.setForeground(new java.awt.Color(255, 255, 255));
        LabelKetEdit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelKetEdit.setText("Keterangan");
        LabelKetEdit.setOpaque(true);
        jPanel2.add(LabelKetEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 380, 101, 27));

        EditKeterangan_input.setColumns(20);
        EditKeterangan_input.setRows(5);
        jScrollPane2.setViewportView(EditKeterangan_input);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 330, -1));

        jButton3.setText("UPDATE");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 440, -1, -1));

        EditStatus_input.setBackground(new java.awt.Color(255, 255, 255));
        EditStatus_input.setFont(new java.awt.Font("Geometr706 BlkCn BT", 0, 14)); // NOI18N
        EditStatus_input.setForeground(new java.awt.Color(0, 0, 0));
        EditStatus_input.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pending", "Proses Desain", "Antri Cetak", "Proses Cetak", "Selesai", "Dikirim", "Dibatalkan" }));
        jPanel2.add(EditStatus_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 220, 27));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 520));
        jPanel2.setVisible(false);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void LabelSubmitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelSubmitMouseEntered
        // TODO add your handling code here:
        LabelSubmit.setBackground(new Color(52, 152, 219));
    }//GEN-LAST:event_LabelSubmitMouseEntered

    private void LabelSubmitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelSubmitMouseExited
        // TODO add your handling code here:
        LabelSubmit.setBackground(new Color(41,128,185));
    }//GEN-LAST:event_LabelSubmitMouseExited

    private void LabelSubmitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelSubmitMouseClicked
        // TODO add your handling code here:
        String allstring = ""+LabelNamaCustomer_input.getText()+LabelJenisBahan_input.getText()+LabelUkuran_input.getText()+LabelNamaSetter_input.getText()+LabelKeterangan_input.getText();
        String specialChars = "/*!@#$%^&*()\"{}_[]|\\?/<>,'";
        System.out.println(allstring);
        for (int i = 0; i < specialChars.length(); i++) {
         if (allstring.contains(specialChars.substring(i, i+1))) {
             JOptionPane.showMessageDialog(null, "ada simbol di input terdeteksi, TIDAK BOLEH");
             return;
         }
        }
        if(LabelNamaCustomer_input.getText().isEmpty()||LabelJenisBahan_input.getText().isEmpty()||LabelUkuran_input.getText().isEmpty()||LabelNamaSetter_input.getText().isEmpty()||LabelQty_input.getText().isEmpty()||LabelKeterangan_input.getText().isEmpty()|LabelHarga_input.getText().isEmpty()||LabelPootnganHarga_input.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "SEMUA HARUS DIISI !!");
            return;
        }
        new write_data(new String[]{"jenis_bahan","ukuran","keterangan","nama_customer","nama_setter","qty"},new String[]{String.format("'%s'", LabelJenisBahan_input.getText()),String.format("'%s'", LabelUkuran_input.getText()),String.format("'%s'", LabelKeterangan_input.getText()),String.format("'%s'", LabelNamaCustomer_input.getText()),String.format("'%s'", LabelNamaSetter_input.getText()),String.format("'%s'", LabelQty_input.getText())},"barang"+Trilogiz.tanggalsekarang).write_data();
        new write_data(new String[]{"pengerjaan","harga","potongan_harga"},new String[]{"'Pending'",String.format("%d", Integer.parseInt(LabelHarga_input.getText())),String.format("%d", Integer.parseInt(LabelPootnganHarga_input.getText()))},"status"+Trilogiz.tanggalsekarang).write_data();
        JOptionPane.showMessageDialog(null, "Proses mendaftarkan ke database selesai, cek log jika ada error");
        read_data.getlastid("barang"+Trilogiz.tanggalsekarang, LabelID_status);
        
    }//GEN-LAST:event_LabelSubmitMouseClicked

    private void LabelHarga_inputKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LabelHarga_inputKeyTyped
        // TODO add your handling code here:
        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_LabelHarga_inputKeyTyped

    private void LabelPootnganHarga_inputKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LabelPootnganHarga_inputKeyTyped
        // TODO add your handling code here:
        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_LabelPootnganHarga_inputKeyTyped

    private void LabelQty_inputKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LabelQty_inputKeyTyped
        // TODO add your handling code here:
        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_LabelQty_inputKeyTyped

    private void LabelCekinputdataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelCekinputdataMouseClicked
        // TODO add your handling code here:
        jPanel2.setVisible(false);
        jPanel1.setVisible(true);
        
    }//GEN-LAST:event_LabelCekinputdataMouseClicked

    private void LabelCekinputdataMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelCekinputdataMouseEntered
        // TODO add your handling code here:
        LabelCekinputdata.setBackground(new Color(52, 152, 219));
    }//GEN-LAST:event_LabelCekinputdataMouseEntered

    private void LabelCekinputdataMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelCekinputdataMouseExited
        // TODO add your handling code here:
        LabelCekinputdata.setBackground(new Color(41,128,185));
    }//GEN-LAST:event_LabelCekinputdataMouseExited

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        dispose();
        new Setter().setVisible(true);
    }//GEN-LAST:event_jButton1MouseClicked

    private void LabelCekdataorderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelCekdataorderMouseClicked
        // TODO add your handling code here:
        jPanel1.setVisible(false);
        jPanel2.setVisible(true);


    }//GEN-LAST:event_LabelCekdataorderMouseClicked

    private void LabelCekdataorderMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelCekdataorderMouseEntered
        // TODO add your handling code here:
        LabelCekdataorder.setBackground(new Color(52, 152, 219));
    }//GEN-LAST:event_LabelCekdataorderMouseEntered

    private void LabelCekdataorderMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelCekdataorderMouseExited
        // TODO add your handling code here:
        LabelCekdataorder.setBackground(new Color(41,128,185));
    }//GEN-LAST:event_LabelCekdataorderMouseExited

    private void EditID_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditID_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EditID_inputActionPerformed

    private void EditID_inputKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EditID_inputKeyTyped
        // TODO add your handling code here:
        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_EditID_inputKeyTyped

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        idnow = Integer.parseInt(EditID_input.getText());
        String[] hasilcek = read_data.singlereaddata(Integer.parseInt(Trilogiz.tanggalsekarang), Integer.parseInt(EditID_input.getText()));
        System.out.println(Arrays.toString(hasilcek));
        if(Arrays.toString(hasilcek).contains("null")){
            JOptionPane.showMessageDialog(null, "ID tidak ada");
        }else{
            for(int i=0;i<hasilcek.length;i++){
                System.out.println(hasilcek[i]);
            }
            EditNamaCustomer_input.setText(hasilcek[0]);
            EditJenisBahan_input.setText(hasilcek[1]);
            EditUkuran_input.setText(hasilcek[2]);
            EditSetter_input.setText(hasilcek[3]);
            EditQty_input.setText(hasilcek[4]);
            EditStatus_input.setSelectedItem(hasilcek[5]);
            Editharga_input.setText(hasilcek[6]);
            EditpotHarga_input.setText(hasilcek[7]);
            EditKeterangan_input.setText(hasilcek[8]);
        }
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        String allstring = ""+EditID_input.getText()+EditJenisBahan_input.getText()+EditKeterangan_input.getText()+EditNamaCustomer_input.getText()+EditQty_input.getText()+EditSetter_input.getText()+EditSetter_input.getText()+EditUkuran_input.getText()+Editharga_input.getText()+EditpotHarga_input.getText();
        String specialChars = "/*!@#$%^&*()\"{}_[]|\\?/<>,'";
        System.out.println(allstring);
        for (int i = 0; i < specialChars.length(); i++) {
         if (allstring.contains(specialChars.substring(i, i+1))) {
             JOptionPane.showMessageDialog(null, "ada simbol di input terdeteksi, TIDAK BOLEH");
             return;
         }
        }
        if(EditID_input.getText().isEmpty()||EditJenisBahan_input.getText().isEmpty()||EditKeterangan_input.getText().isEmpty()||EditNamaCustomer_input.getText().isEmpty()||EditQty_input.getText().isEmpty()||EditSetter_input.getText().isEmpty()||EditUkuran_input.getText().isEmpty()||Editharga_input.getText().isEmpty()||EditpotHarga_input.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "SEMUA HARUS DIISI !!");
            return;
        }
        write_data.updatedata_barang("barang"+Trilogiz.tanggalsekarang, EditJenisBahan_input.getText(), EditUkuran_input.getText(), EditKeterangan_input.getText(), EditNamaCustomer_input.getText(), EditSetter_input.getText(), Integer.parseInt(EditQty_input.getText()), idnow);
        write_data.update_data_status("status"+Trilogiz.tanggalsekarang, EditStatus_input.getSelectedItem().toString(), Integer.parseInt(Editharga_input.getText()), Integer.parseInt(EditpotHarga_input.getText()), idnow);
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void EditQty_inputKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EditQty_inputKeyTyped
        // TODO add your handling code here:
        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_EditQty_inputKeyTyped

    private void Editharga_inputKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Editharga_inputKeyTyped
        // TODO add your handling code here:
        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_Editharga_inputKeyTyped

    private void EditpotHarga_inputKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EditpotHarga_inputKeyTyped
        // TODO add your handling code here:
        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_EditpotHarga_inputKeyTyped

    private void LabelTanggal_statusDateChanged(org.freixas.jcalendar.DateEvent evt) {//GEN-FIRST:event_LabelTanggal_statusDateChanged
        // TODO add your handling code here:
        String tglskrg = new SimpleDateFormat("yyyyMMdd").format(LabelTanggal_status.getDate());
        tanggalsekarangDate = new GregorianCalendar(Integer.parseInt(tglskrg.substring(0,4)), Integer.parseInt(tglskrg.substring(4,6))-1, Integer.parseInt(tglskrg.substring(6,8))).getTime();
               //LabelTanggal_status.setDate(date);
               
               //System.err.println(LabelTanggal_status.getDate());
               System.out.println(tglskrg);
               Trilogiz.tanggalsekarang = tglskrg;
    }//GEN-LAST:event_LabelTanggal_statusDateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and4 feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Setter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Setter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Setter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Setter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Setter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField EditID_input;
    private javax.swing.JTextField EditJenisBahan_input;
    private javax.swing.JTextArea EditKeterangan_input;
    private javax.swing.JTextField EditNamaCustomer_input;
    private javax.swing.JTextField EditQty_input;
    private javax.swing.JTextField EditSetter_input;
    private javax.swing.JComboBox<String> EditStatus_input;
    private javax.swing.JTextField EditUkuran_input;
    private javax.swing.JTextField Editharga_input;
    private javax.swing.JTextField EditpotHarga_input;
    private javax.swing.JLabel LabelCekdataorder;
    private javax.swing.JLabel LabelCekinputdata;
    private javax.swing.JLabel LabelHarga;
    private javax.swing.JLabel LabelHargaEdit;
    private javax.swing.JTextField LabelHarga_input;
    private javax.swing.JLabel LabelID;
    private javax.swing.JLabel LabelIDEdit;
    private javax.swing.JLabel LabelID_status;
    private javax.swing.JLabel LabelJenisBahan;
    private javax.swing.JLabel LabelJenisBahanEdit;
    private javax.swing.JTextField LabelJenisBahan_input;
    private javax.swing.JLabel LabelJob;
    private javax.swing.JLabel LabelJob_status;
    private javax.swing.JLabel LabelKetEdit;
    private javax.swing.JLabel LabelKeterangan1;
    private javax.swing.JTextArea LabelKeterangan_input;
    private javax.swing.JLabel LabelNama;
    private javax.swing.JLabel LabelNamaCustomer;
    private javax.swing.JTextField LabelNamaCustomer_input;
    private javax.swing.JLabel LabelNamaSetter;
    private javax.swing.JTextField LabelNamaSetter_input;
    private javax.swing.JLabel LabelNama_status;
    private javax.swing.JLabel LabelPootnganHarga;
    private javax.swing.JTextField LabelPootnganHarga_input;
    private javax.swing.JLabel LabelQty;
    private javax.swing.JLabel LabelQtyEdit1;
    private javax.swing.JTextField LabelQty_input;
    private javax.swing.JLabel LabelSetterEdit;
    private javax.swing.JLabel LabelStatusEdit;
    private javax.swing.JLabel LabelSubmit;
    private javax.swing.JLabel LabelTanggal;
    private org.freixas.jcalendar.JCalendarCombo LabelTanggal_status;
    private javax.swing.JLabel LabelUkuran;
    private javax.swing.JLabel LabelUkuranEdit;
    private javax.swing.JTextField LabelUkuran_input;
    private javax.swing.JLabel LabelUsername;
    private javax.swing.JLabel LabelUsername_status;
    private javax.swing.JLabel LabelpotHargaEdit;
    private javax.swing.JLabel NamaCustEdit;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel userpanel;
    // End of variables declaration//GEN-END:variables
}
